### ISSUE TITLE
Explain you need to hit Enter twice after %load

### ISSUE THREAD

**Issue by smythp** [Iota-School/nonvisual_data_science#13]

**Comment by NV-Codes** [comment]
I created Pull Request #16 to address this issue.

**Comment by smythp** [comment]
Great contribution, thank you. By the way, if you add the line "Resolves #13" to a commit message or a comment in a pull request, it will automatically close the issue, which is pretty cool. You can read about it here:  https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
